[project]
name = "raglens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "ipykernel>=6.16.2",
]
requires-python = ">=3.10,<4.0"
